import { randomBytes } from "node:crypto";
import { chmodSync, readFileSync, writeFileSync } from "node:fs";

// Shared OAuth2 helper for google-calendar.ts and the /api/auth/google/*
// routes in index.ts — token exchange/refresh and persisting the refresh
// token are cross-cutting, not specific to the calendar adapter (any future
// Google service would reuse this same single-account token).

const REDIRECT_URI = "http://localhost:3001/api/auth/google/callback";
const SCOPE = "https://www.googleapis.com/auth/calendar.readonly";
const TOKEN_URL = "https://oauth2.googleapis.com/token";

// CSRF guard (RFC 6749 §10.12): buildAuthUrl mints a one-time state value
// and callers must pass it back to verifyAndConsumeState before the
// callback trusts the code. A single in-memory slot is enough for one local
// user with one in-flight Connect click at a time — a multi-user deployment
// would need this keyed per-session instead of module-global.
let pendingState: string | null = null;

export function buildAuthUrl(): string {
  const clientId = process.env.GOOGLE_CLIENT_ID;
  if (!clientId) throw new Error("GOOGLE_CLIENT_ID not configured");
  pendingState = randomBytes(16).toString("hex");
  const params = new URLSearchParams({
    client_id: clientId,
    redirect_uri: REDIRECT_URI,
    response_type: "code",
    scope: SCOPE,
    access_type: "offline",
    prompt: "consent", // forces a refresh_token even on a re-consent
    state: pendingState,
  });
  return `https://accounts.google.com/o/oauth2/v2/auth?${params}`;
}

// One-time check, consumed regardless of outcome so a state value can't be
// replayed.
export function verifyAndConsumeState(state: string): boolean {
  const valid = pendingState !== null && state === pendingState;
  pendingState = null;
  return valid;
}

export async function exchangeCodeForRefreshToken(code: string): Promise<string> {
  const clientId = process.env.GOOGLE_CLIENT_ID;
  const clientSecret = process.env.GOOGLE_CLIENT_SECRET;
  if (!clientId || !clientSecret) throw new Error("GOOGLE_CLIENT_ID/GOOGLE_CLIENT_SECRET not configured");

  const res = await fetch(TOKEN_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      code,
      client_id: clientId,
      client_secret: clientSecret,
      redirect_uri: REDIRECT_URI,
      grant_type: "authorization_code",
    }),
  });
  if (!res.ok) throw new Error(`Google token exchange failed: ${res.status} ${await res.text()}`);
  const body = await res.json();
  if (!body.refresh_token) {
    throw new Error(
      "Google didn't return a refresh token — revoke this app's access at " +
        "https://myaccount.google.com/permissions and connect again",
    );
  }
  return body.refresh_token as string;
}

// A fresh access token per capability call rather than caching one against
// its expiry — call volume here is one manual Sync click at a time, so the
// extra round-trip isn't worth the bookkeeping. ponytail: cache with expiry
// if this ever gets chatty enough to matter.
export async function getAccessToken(): Promise<string> {
  const clientId = process.env.GOOGLE_CLIENT_ID;
  const clientSecret = process.env.GOOGLE_CLIENT_SECRET;
  const refreshToken = process.env.GOOGLE_REFRESH_TOKEN;
  if (!clientId || !clientSecret || !refreshToken) {
    throw new Error("Google Calendar not connected — connect it from Settings first");
  }

  const res = await fetch(TOKEN_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      refresh_token: refreshToken,
      client_id: clientId,
      client_secret: clientSecret,
      grant_type: "refresh_token",
    }),
  });
  if (!res.ok) throw new Error(`Google token refresh failed: ${res.status} ${await res.text()}`);
  const body = await res.json();
  return body.access_token as string;
}

// The one credential in this app that's generated by a flow instead of
// hand-pasted into .env by the user (GITHUB_TOKEN, the weather adapter's
// none-at-all) — so persisting it is the app's job. Updates the key in
// place if already present, else appends it; also sets process.env
// directly so it takes effect without a server restart. Written owner-only
// (0600) since it holds a live refresh token — writeFileSync's mode option
// only applies when the file doesn't already exist, so an explicit chmod
// follows to cover the update-in-place case too.
export function persistRefreshToken(token: string): void {
  process.env.GOOGLE_REFRESH_TOKEN = token;

  const envPath = new URL("../.env", import.meta.url);
  let content = "";
  try {
    content = readFileSync(envPath, "utf-8");
  } catch {
    // no .env yet
  }
  const line = `GOOGLE_REFRESH_TOKEN=${token}`;
  const updated = /^GOOGLE_REFRESH_TOKEN=.*$/m.test(content)
    ? content.replace(/^GOOGLE_REFRESH_TOKEN=.*$/m, line)
    : content.trimEnd().length > 0
      ? `${content.trimEnd()}\n${line}\n`
      : `${line}\n`;
  writeFileSync(envPath, updated, { mode: 0o600 });
  chmodSync(envPath, 0o600);
}
