import type { BlockResult, ListResult, WeekResult } from "../../src/types.ts";
import { CAPABILITIES } from "../../src/types.ts";
import { getAccessToken } from "../googleAuth.ts";

// Single-account OAuth2, not a static token like GITHUB_TOKEN — the refresh
// token is generated by the /api/auth/google/* flow (server/index.ts), not
// hand-pasted by the user, see googleAuth.ts.
export const requiredEnvVars = ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_REFRESH_TOKEN"];

const EVENTS_URL = "https://www.googleapis.com/calendar/v3/calendars/primary/events";
const UPCOMING_LIMIT = 10;
const UPCOMING_HORIZON_DAYS = 30;

interface GEvent {
  summary?: string;
  start: { date?: string; dateTime?: string }; // date = all-day, dateTime = timed
}

async function listEvents(timeMin: Date, timeMax: Date, maxResults: number): Promise<GEvent[]> {
  const accessToken = await getAccessToken();
  const params = new URLSearchParams({
    timeMin: timeMin.toISOString(),
    timeMax: timeMax.toISOString(),
    singleEvents: "true", // expands recurring events into concrete occurrences
    orderBy: "startTime",
    maxResults: String(maxResults),
  });
  const res = await fetch(`${EVENTS_URL}?${params}`, { headers: { Authorization: `Bearer ${accessToken}` } });
  if (!res.ok) throw new Error(`Google Calendar API error: ${res.status}`);
  const body = await res.json();
  return (body.items ?? []) as GEvent[];
}

function eventDate(e: GEvent): string {
  return (e.start.date ?? e.start.dateTime ?? "").slice(0, 10);
}

async function upcomingEvents(): Promise<ListResult> {
  const now = new Date();
  const horizon = new Date(now.getTime() + UPCOMING_HORIZON_DAYS * 24 * 60 * 60 * 1000);
  const events = await listEvents(now, horizon, UPCOMING_LIMIT);
  return { items: events.map((e) => ({ title: e.summary ?? "(untitled)", date: eventDate(e) })) };
}

async function thisWeek(): Promise<WeekResult> {
  const start = new Date();
  start.setHours(0, 0, 0, 0);
  const end = new Date(start.getTime() + 7 * 24 * 60 * 60 * 1000);
  const events = await listEvents(start, end, 50);

  const days = Array.from({ length: 7 }, (_, i) => {
    const date = new Date(start.getTime() + i * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
    return { date, entries: events.filter((e) => eventDate(e) === date).map((e) => ({ title: e.summary ?? "(untitled)" })) };
  });
  return { days };
}

type CapabilityFn = () => Promise<BlockResult>;

const CAPABILITY_FNS: Record<string, CapabilityFn> = {
  "upcoming-events": upcomingEvents,
  "this-week": thisWeek,
};

export async function runCapability(capabilityId: string, _params: Record<string, string>): Promise<BlockResult | null> {
  const known = CAPABILITIES["google-calendar"].some((c) => c.id === capabilityId);
  if (!known) return null;
  return CAPABILITY_FNS[capabilityId]();
}
